CREATE TABLE TIPO
(
	COD_TIPO INT NOT NULL IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE SUBTIPO
(
	COD_SUBTIPO INT NOT NULL IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE ARTICULO
(
	CODIGO_ARTICULO INT NOT NULL IDENTITY PRIMARY KEY,
	COD_TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPO(COD_TIPO),
	COD_SUBTIPO INT NOT NULL FOREIGN KEY REFERENCES SUBTIPO(COD_SUBTIPO),
	NOMBRE VARCHAR(100) NOT NULL
)	


CREATE TABLE SUCURSAL 
(
	COD_SUCURSAL INT NOT NULL IDENTITY PRIMARY KEY, 
	NOMBRE VARCHAR(50) NOT NULL
)	

CREATE TABLE EXISTENCIAS
(
	COD_EXISTENCIA INT NOT NULL IDENTITY PRIMARY KEY,
	COD_SUCURSAL INT NOT NULL FOREIGN KEY REFERENCES SUCURSAL(COD_SUCURSAL),
	CODIGO_ARTICULO INT NOT NULL FOREIGN KEY REFERENCES ARTICULO(CODIGO_ARTICULO),
	EXISTENCIAS INT NOT NULL
)

CREATE TABLE PROMOCION
(
	 COD_PROMOCION INT NOT NULL IDENTITY PRIMARY KEY,
	 NOMBRE VARCHAR(200) NOT NULL,
	 FECHA_DESDE DATETIME NOT NULL, 
	 FEHCA_HASTA DATETIME NOT NULL
)

CREATE TABLE PROMOCION_ARTICULO
(
	COD_PROMOCION_ARTICULO INT NOT NULL IDENTITY PRIMARY KEY,
	COD_PROMOCION INT NOT NULL FOREIGN KEY REFERENCES PROMOCION(COD_PROMOCION),
	CODIGO_ARTICULO INT NOT NULL FOREIGN KEY REFERENCES ARTICULO(CODIGO_ARTICULO),
	PUNTOS INT NOT NULL,
	PRECIO DECIMAL(18,2) NOT NULL
)

CREATE TABLE CANJE
(
	COD_CANJE INT NOT NULL IDENTITY PRIMARY KEY,
	COD_PROMOCION_ARTICULO INT NOT NULL FOREIGN KEY REFERENCES PROMOCION_ARTICULO(COD_PROMOCION_ARTICULO),
	CODIGO_ARTICULO INT NOT NULL FOREIGN KEY REFERENCES ARTICULO(CODIGO_ARTICULO),
	COD_PROMOCION INT NOT NULL FOREIGN KEY REFERENCES PROMOCION(COD_PROMOCION),
	PUNTOS INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(18, 2) NOT NULL,
	FECHA DATETIME NOT NULL,
	OBSERVACIONES VARCHAR(2000)
)